### ISSUE TITLE
Restructure buildpack: Create php-fpm buildpack 

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/php-fpm#3]
## Context
Per [PHP RFC 0001](https://github.com/paketo-buildpacks/rfcs/blob/main/text/php/0001-restructure.md) we are restructuring the PHP language family of buildpacks to make them more modular, up-to-date, and as a result, maintainable.

Currently, the [PHP Web buildpack ](https://github.com/paketo-buildpacks/php-web) is responsible for configuring and running PHP applications across built-in PHP servers, HTTPD, NGINX, as well as supporting FPM process managers. The goal of this issue is to separate the concerns within PHP Web into individual buildpacks.

## Issue
This issue is to add a new buildpack, named `php-fpm`, which will be responsible for generating a config file  related to FPM (FastCGI Process Manager). 

Logic to support FPM currently lives within the [PHP Web buildpack ](https://github.com/paketo-buildpacks/php-web/blob/v0.1.3/features/phpfpm.go) and should be moved into this new buildpack. This buildpack will be solely responsible for setting up php-fpm config. The php-httpd and php-nginx buildpacks will be responsible for _using_ php-fpm in their start commands.

- [x] API: The buildpack should `provide php-fpm` and `require php` at  build-time and launch-time. 

 - [x] This buildpack will configure  a `php-fpm-config.conf` file (in `php.ini` syntax) located inside `/layers/paketo-buildpacks_php-fpm/` for consumption by other buildpacks (php-httpd or php-nginx)

- [x] Config File:
  - [x] The `php-fpm.conf` file must accept requests on a tcp/ip socket by default
  - [X] It must `include` custom `fpm` configs specified by the user (e.g. via env variables or specific location in the app). See https://github.com/paketo-buildpacks/php-web/blob/5bcb1f838fdbf16964e235d9445920cd8e3fbcc1/features/phpfpm.go#L92-L104 for how this is done in PHP Web.
  - [x] It must also expose the `php-fpm.conf` file path via an environment variable at both build/launch.  (The name of the environment variable is an implementation detail to be decided by implementer.)

- [x] Packit: This buildpack should be written using the [packit library](https://github.com/paketo-buildpacks/packit).

- [x] README: Make sure a README is added that conveys context about the buildpack in a manner consistent with other Paketo buildpacks.
- [x] Add a `[[buildpack.licences]]` section to the `buildpack.toml`.
- [x] Support env var configuration instead of buildpack.yml (See [PHP buildpack RFC #2](https://github.com/paketo-buildpacks/rfcs/blob/main/text/php/0002-buildpack-yml-to-env-var.md))
- [x] Buildpack API Version: This buildpack should be written using [Buildpack API 0.7](https://github.com/buildpacks/spec/releases/tag/buildpack%2Fv0.7)

This issue can be transferred to the appropriate repository (paketo-buildpacks/php-fpm), once it has been created.

## Acceptance
1. I can build an app with php-dist, this buildpack, and the build plan buildpack that requires php-fpm at launch. The logs show a FPM config file is being generated. The path to that config file has been set in a Shared Build/Launch environment variable. When I go onto the resulting container, I can see a `php-fpm.config` file in `/layers/paketo-buildpacks_php-fpm/`, and its path is available in the environment variable.

**Comment by fg-j** [comment]
From [this thread](https://paketobuildpacks.slack.com/archives/CUD6TBJAE/p1638903191005500)

> In the new design, php-dist is responsible for contributing php.ini. Downstream buildpacks must use utilities that are part of the php distribution whenever possible to extract information (e.g. path to php.ini) rather than non-standard environment variables set by upstream buildpacks.
